# Generated by Django 4.2.5 on 2023-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, help_text='Enter username', max_length=150, null=True, verbose_name='Username')),
                ('name', models.CharField(blank=True, help_text='Enter name', max_length=150, null=True, verbose_name='Name')),
                ('telegram_id', models.IntegerField(db_index=True, help_text='Enter Telegram ID', unique=True, verbose_name='Telegram ID')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', max_length=5, verbose_name='Language')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BotUser',
                'verbose_name_plural': 'BotUsers',
                'db_table': 'BotUser',
            },
        ),
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(choices=[('oak', 'OAK uchun'), ('res', 'Respublika Konferensiya'), ('xal', 'Xalqaro ilmiy jurnal'), ('konf', 'Xalqaro konferensiya')], max_length=100, verbose_name='Maqola')),
                ('xizmat', models.CharField(choices=[('yoz', 'Yozib berish '), ('yoz_chop', 'Yozib berish va Chop etish'), ('chop', 'Chop etish')], max_length=100, verbose_name="Xizmat ko'rsatish")),
                ('sohalar', models.CharField(choices=[('tex', 'Texnika'), ('ped', 'Pedagogika'), ('eco', 'Iqtisodiyot'), ('med', 'Tibbiyot')], max_length=100, verbose_name='Sohalar')),
                ('telefon_raqam', models.CharField(help_text='Telefon nomerni kiriting', max_length=20, verbose_name='Telefon raqam')),
                ('ish_joyi', models.CharField(help_text='Lavozim va ish joyingizni kiriting', max_length=200, verbose_name='Ish joyi va lavozimi')),
            ],
        ),
    ]
