"""
Django settings for newscientist project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@n1q46-*b=(u-74y2-lngwks+3#90o-w&hn@1=z6isq^ou+zz4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'storages', 
    'myapp.apps.MyappConfig',
    # 'import_export',
    # 'rest_framework',
    # 'boto3',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newscientist.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newscientist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

#########  Language Setting #######
LANGUAGE_CODE = 'en-us'
# from django.utils.translation import gettext_lazy as _
# LANGUAGE_CODE = 'en-us'
# LANGUAGES = (
#     ('en', 'English'),
#     ('uz', 'Uzbek'),
#     ('ru', 'Russian'),
# )
# LOCALE_PATHS = [
#     BASE_DIR / 'locale/',
# ]
# MODELTRANSLATION_DEFAULT_LANGUAGE = 'uz'
# MODELTRANSLATION_LANGUAGES = ('uz', 'ru')
##################

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
import os

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




############### Django Jazzmin ###########

JAZZMIN_SETTINGS = {
    "site_title": "New Scientist admin",
    "site_header": "New Scientist",
    "site_brand": "New Scientist",
    "site_logo": None,
    "login_logo": None,
    "site_logo_dark": None,
    "site_logo_classes": None,
    "site_icon": None,
    "welcome_sign": "Welcome to New Scientists",
    "copyright": "New Scientist",
    "search_model": ["myapp.Users"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Admin", "url": "https://t.me/siddiqov_bobur", "new_window": True},

    ],

    "usermenu_links": [
         {"name": "Admin", "url": "https://t.me/siddiqov_bobur", "new_window": True},
    ], 
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to":["auth", "books", "books.author", "books.book"],
    
    "custom_links": {
        "books": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "myapp.BotUser": "fas fa-user-tie",
        "myapp.Maqola": "fas fa-shopping-bag",
    },


    "default_icon_parents": " fas fa-chervon-circle-right",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": False,

    "custom_css": None,
    "custom_js": None,

    "use_google_fonts_cdn": True,

    "show_ui_builder": False,


    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collabsible", "auth.group": "vertical_tabs"},
    # "language_chooser": True,
}
